window.portfolios = [
    {
        "TabLabel": "Brightvision.se",
        "Contents": [
            {
                "ContentLabel": "Brightvision customer portal",
                "ContentImage": "http://i1031.photobucket.com/albums/y374/Darrel_D_Abello/portal-brightvision_zpsodp3xjc6.png",
                "Content": "A simple web app for managing meetings of the user"
            }
        ]
    },

    {
        "TabLabel": "Angebot 2.0",
        "Contents": [
            {
                "ContentLabel": "Angebot Quote Dashboard",
                "ContentImage": "http://i1031.photobucket.com/albums/y374/Darrel_D_Abello/angebot1_zpsaosu0599.png",
                "Content": "One of the main objective of angebot is to manage aquotes, so here is the screen where users manage their quotes."
            },
            {
                "ContentLabel": "Quote editor fig.1",
                "ContentImage": "http://i1031.photobucket.com/albums/y374/Darrel_D_Abello/angebot3_zpst3yeey3g.png",
                "Content": "This is the top part of the quote editor screen, here you can add title and contents to the quotes, set the recipients of the quotes."
            },
            {
                "ContentLabel": "Quote editor fig.2",
                "ContentImage": "http://i1031.photobucket.com/albums/y374/Darrel_D_Abello/angebot2_zpsaeg6kbfx.png",
                "Content": "This is bottom part of the quote editor where you add items in to the quote, users can communicate to the clients using the comments tab, users can also attach files to the quote and view quote activities or quote updates."
            },
            {
                "ContentLabel": "Quote preview fig.1",
                "ContentImage": "http://i1031.photobucket.com/albums/y374/Darrel_D_Abello/angebot4_zpsn4z9fuvu.png",
                "Content": "The quote preview screen is the same with what the clients see when they view the quote they received, except the clients has an accept button at the bottom part. the color schemes and logo of this page depends on the company settings. this page is generated by the back end."
            },
            {
                "ContentLabel": "Quote preview fig.2",
                "ContentImage": "http://i1031.photobucket.com/albums/y374/Darrel_D_Abello/angebot5_zpsc1ymz9mn.png",
                "Content": "At the bottom part of the quote preview, clients can check the details of each items added in the quote. clients can also send a comment back to the quote creator, the users are not required to login to anything to get their identity, so we created a custom token to identify the user who sends the comment."
            },
            {
                "ContentLabel": "Quote preview fig.3",
                "ContentImage": "http://i1031.photobucket.com/albums/y374/Darrel_D_Abello/angebot7_zpsrmt4ryk9.png",
                "Content": "Like i said in quote preview fig.2, this is an actual screen shot from user clients view, they can send comments back to the quote creator and accept the sent quote if the details of quote is a good to go for them."
            },
            {
                "ContentLabel": "User client email view",
                "ContentImage": "http://i1031.photobucket.com/albums/y374/Darrel_D_Abello/angebot6_zpsqpginche.png",
                "Content": "A sample screen shot of the email the user received when the quote is sent by the quote creator, containing the summary of the quote."
            },
            {
                "ContentLabel": "Client view of all his/her quotes",
                "ContentImage": "http://i1031.photobucket.com/albums/y374/Darrel_D_Abello/angebot8_zpswzwns72m.png",
                "Content": "A page where clients can view the list of quotes associated to them (clients of the users are not required to login to the app, they are authenticated with the customized token attached to the email they received."
            }
        ]
    }
]
            